Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home' 
  get 'best1440', to: 'pages#best1440'
  get 'best4K', to: 'pages#best4K'
  get 'best1080', to: 'pages#best1080'
  get 'bestGPU', to: 'pages#bestGPU'
  get 'bestRAM', to: 'pages#bestRAM'
  get 'best4K', to: 'pages#best4K'
  get 'mbamd', to: 'pages#mbamd'
  get 'mbIntel', to: 'pages#mbIntel'
  get 'bestRAM', to: 'pages#bestRAM'
  get 'screen', to: 'pages#screen'
  get 'bestNVME', to: 'pages#bestNVME'
  get 'bestWATT', to: 'pages#bestWATT'
  get 'bestAIO', to: 'pages#bestAIO'
  get 'mouse', to: 'pages#mouse'
  get 'bestCPU', to: 'pages#bestCPU'
  get 'bestbox', to: 'pages#bestbox'
  get 'keyboard', to: 'pages#keyboard'
  get 'bestGPU4K', to: 'pages#bestGPU4K'
  get 'bestGPU2K', to: 'pages#bestGPU2K'
  get 'bestGPUHD', to: 'pages#bestGPUHD'
  get 'g3090TI', to: 'pages#g3090TI'
  get 'g3090', to: 'pages#g3090'
  get 'g3080TI', to: 'pages#g3080TI'
  get 'g3080', to: 'pages#g3080'
  get 'g6900XT', to: 'pages#g6900XT'
  get 'g6800XT', to: 'pages#g6800XT'
  get 'g6800', to: 'pages#g6800'
  get 'best1440LOW', to: 'pages#best1440LOW'
  get 'best1440choise', to: 'pages#best1440choise'
  get 'best4KLOW', to: 'pages#best4KLOW'
  get 'best4KLOW', to: 'pages#best4KLOW'
  get 'best4Kchoise', to: 'pages#best4Kchoise'
  
end
